[package]
name = "gladius_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "gladius_proc_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.79", features = ["extra-traits"] }
proc-macro2 = "1.0.87"